### ISSUE TITLE
Q1.1: add bit-vector solution

### ISSUE THREAD

**Issue by ele7ija** [krlv/ctci-go#7]
Hi, I have written a solution that doesn't use additional data structures and has O(n) complexity.

Cannot make a PR tho because it's forbidden. 

Anyway, I'll attach the code below since it's dead simple.

```go
// IsUniqueBits determines if a string has all unique chars (only works for ASCII)
// This solution doesn't utilize any additional data structures and has O(n) time complexity
func IsUniqueBits(s string) bool {

	s = strings.ToLower(s)
	var vector int32
	sBytes := []byte(s) // only for ASCII
	for _, sByte := range sBytes {
		index := sByte - 'a'
		mask := int32(1 << index)
		if (vector & mask) == mask {
			return false
		}
		vector = vector | mask
	}
	return true
}
```

**Comment by ele7ija** [comment]
will create a fork instead

**Comment by krlv** [comment]
Thanks for the contribution @ele7ija . Not sure why creating PR is forbidden for you, I've re-checked security configs, it should be fine. 

Regarding the proposed solution, I would also mention in the comments that it will not work for case-sensitive string.
Also, If you're going to open a PR, please add tests for this implementation.
